### ISSUE TITLE
Hubcap creates a very large number of branches on the hub.getdbt.com repo

### ISSUE THREAD

**Issue by clrcrl** [dbt-labs/hubcap#19]
<img width="287" alt="Screen Shot 2020-10-07 at 10 39 28 AM" src="https://user-images.githubusercontent.com/20294432/95346041-64d2a400-0889-11eb-90df-ee23777f6a08.png">

https://github.com/fishtown-analytics/hub.getdbt.com/branches

This feels like too many branches to me :)

**Comment by aaronsteers** [comment]
😄  
![image](https://user-images.githubusercontent.com/18150651/121760340-1a23be80-cadf-11eb-8acf-1d54c1dd6d32.png)

**Comment by jtcohen6** [comment]
Hopefully closed by https://github.com/dbt-labs/hubcap/pull/42

**Comment by drewbanin** [comment]
again, i can only apologize
