### ISSUE TITLE
Hubcap fails if package does not have a `master` branch

### ISSUE THREAD

**Issue by clrcrl** [dbt-labs/hubcap#21]
Note that this is becoming more problematic since GitHub defaults to using `main` now, so more packages will be created _without_ the `master` branch

[Relevant code](https://github.com/fishtown-analytics/hubcap/blob/master/hubcap.py#L53).

**Comment by clrcrl** [comment]
Fixed by #22

**Comment by VersusFacit** [comment]
This has been fixed but we should at some point move this to a main-first repo.
