### ISSUE TITLE
Hub seems to have stopped updating?

### ISSUE THREAD

**Issue by rlh1994** [dbt-labs/hubcap#288]
Hi, just noticed that we published a new release of `snowplow_utils` earlier today and it's still not showing on the hub, nor is there a PR in https://github.com/dbt-labs/hub.getdbt.com/pulls raised for it. I also noticed that the last PR made that added https://github.com/BfdCampos/source_db/ seems to also not be showing in the front end hub site?

Not sure if something has gone wrong of if there is a reason it's paused.

**Comment by joellabes** [comment]
Fixed now sorry!
