### ISSUE TITLE
Get package dependencies for specific release tag

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/hubcap#44]
(Similar to #21)

Hubcap uses the default branch, rather than the specific release, to get information about `packages` (dependencies). Instead, for each tagged release it's adding, it should check out that tag before introspecting packages.

This is causing issues right now for `fivetran_utils`. They can't change the default branch (it's pointed to by some older versions of other packages), so they want to cut releases from non-default branches instead. Everything works except for the `packages` dict created by Hubcap.

**Comment by jtcohen6** [comment]
Did not work for latest `fivetran_utils` release: https://github.com/dbt-labs/hub.getdbt.com/pull/783

**Comment by VersusFacit** [comment]
If this is still an outstanding issue, I suspect it could be solved by moving around logic. Have the script parse out dependencies before specs are made in each tag rather than at first. It would just take a bit of shuffling code around. The tools are all there.

**Comment by jtcohen6** [comment]
Agree! I believe this is still outstanding. We can confirm with the next `fivetran_utils` release, since that package is the prime example of this behavior.

**Comment by VersusFacit** [comment]
@jtcohen6 PR 74 aims to address this once and for all. I did test that it's successful determining the specific packages.yml  contents for a given tag. Want to put this on your radar because if manual intervention is needed after merging this, the PR didn't fix it.
