### ISSUE TITLE
Generate project specification without dbt

### ISSUE THREAD

**Issue by VersusFacit** [dbt-labs/hubcap#53]
## Problem
dbt expectations cannot merge the newest version of their package to `hub.getdbt.com` because the dbt version employed by this repo's build script requires an incompatible version of core.

The script errors out at setup.

## Background

To generate project specifications (i.e. the information used to generate project pages on https://hub.getdbt.com/), `hubcap.py` uses `dbt` itself to run shell commands and extract project information. 

Among other things, this requires a phony dbt profile and a specific dbt version (see `/requirements.txt`). This introduces possible conflict with any packages using a `require-dbt-version` configuration tag in their `dbt_project.yml`. 

As mentioned, dbt expectations is blocked from pushing their newest release because their [pinned dbt version](https://github.com/calogica/dbt-expectations/blob/e47358d5ee5f162457fd4b40aa9ea84d8879ea93/dbt_project.yml#L8) is not compatible with the version of dbt we use in the hubcap build script.

![image](https://user-images.githubusercontent.com/67295367/127452318-d7e7c448-5a10-4250-b188-92d0a344edb2.png)

## Solution

All functionality performed by dbt can be done using familiar Python system libraries and yaml parsing files. Let's remove Core from this build script.

Thankfully, the two files which hold this information are both yaml files located by design at root level of a dbt project--`dbt_project.yml` and `packages.yml`. Yaml parsing libraries should do the trick to put together a specification and a dependency chain.

As a bonus, any modularization of these components will be appreciated in the now and the future.

## Outcomes

- we unblock the dbt expectations team
- we insulate ourselves from this danger

**Comment by clausherther** [comment]
Hello! Just wanted to check in on when we might be able to merge this to get dbt hub back in sync? Thanks!

**Comment by VersusFacit** [comment]
Addressed by #61 . dbt expectations has been back in sync after a manual merge some weeks ago, but also will now automatically sync as before.
