### ISSUE TITLE
Feature: Create a dbt-labs ci user and have them make commits

### ISSUE THREAD

**Issue by VersusFacit** [dbt-labs/hubcap#66]
Currently, we have Drew's user account supporting the access of private repos and running the script. He has an api token fixed to his name among other things.

My gut tells me this should actually be a dedicated ci user rather than something to Drew himself. If nothing else, it's a bit odd to see his face on the hub package version commits. More seriously, having a dedicated user makes it easier to act securely and without needing to bother Drew about such things in the future case other API tokens and such are needed. We can also democratize access to the pipeline across the team.

**Comment by dbeatty10** [comment]
Resolved by [#66](https://github.com/dbt-labs/hubcap/issues/152)

<img width="695" alt="image" src="https://user-images.githubusercontent.com/44704949/200067118-5a96153b-a1f4-4b38-bd34-9d635012fbdb.png">
