### ISSUE TITLE
Feature: Add docs and readme

### ISSUE THREAD

**Issue by VersusFacit** [dbt-labs/hubcap#67]
I added some comments to hubcap during the refactor but that's just the basics. I think it would be swell to add how the script works, notes about the ecosystem, user directions that dovetail.

Documentation is endless, so here's my proposed scope for this issue:
- briefly describe the overall workflow architecture to help new users understand the package ecosystem, especially those who want to contribute packages
- a link to notes about adding a repo
- notes on adding a new package to the hub
- contribution notes for the repo itself

**Comment by dbeatty10** [comment]
Calling these three docs as sufficient to cover this issue:
- https://github.com/dbt-labs/hubcap/blob/main/README.md
- https://github.com/dbt-labs/hubcap/blob/main/CONTRIBUTING.md
- https://github.com/dbt-labs/hubcap/blob/main/RELEASE.md
