### ISSUE TITLE
Feature: Codify package config guidelines

### ISSUE THREAD

**Issue by VersusFacit** [dbt-labs/hubcap#69]
Hey team, we have been discussing there being rules for how a plugin project should look for it to be added to the hub. Here's what I've got so far:
- has a dbt_project.yml with a name
- if packages.yml exists, it lives at the root dir of the package
- the package repo should not be private
- prefer main to master for parsing out commits (perhaps have a way for packages to specify the branch of their choice)

Note: I had originally framed this to myself as requiring a `main` branch, but on second thought, I think it's better to prioritize main to master in the script logic or perhaps even just having some kind of config file in the user package repo's as a possible override if they want to specify the exact branch for us to use when considering new versions. `main` is already prioritized by GitHub and we can document that `master` has been deprecated but is still supported (since any branch can be used). That way, we don't frustrate package maintainers that haven't yet made the switch (plenty of shops are still slowly but surely transitioning over).

What other things should be added to docs about what a basic package should look like?

**Comment by dbeatty10** [comment]
Fixed by https://github.com/dbt-labs/hubcap/pull/139
